-- Add students.department_code linked to departments.
-- SQL Server (idempotent)

IF OBJECT_ID(N'dbo.students', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.students', N'department_code') IS NULL ALTER TABLE [dbo].[students] ADD [department_code] NVARCHAR(20) NULL;

-- Prevent FK creation failure from orphan department codes in existing rows.
IF OBJECT_ID(N'dbo.students', N'U') IS NOT NULL AND OBJECT_ID(N'dbo.departments', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.students', N'department_code') IS NOT NULL AND COL_LENGTH(N'dbo.departments', N'department_code') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_key_columns fkc INNER JOIN sys.columns pc ON fkc.parent_object_id = pc.object_id AND fkc.parent_column_id = pc.column_id INNER JOIN sys.columns rc ON fkc.referenced_object_id = rc.object_id AND fkc.referenced_column_id = rc.column_id WHERE fkc.parent_object_id = OBJECT_ID(N'dbo.students', N'U') AND pc.name = N'department_code' AND fkc.referenced_object_id = OBJECT_ID(N'dbo.departments', N'U') AND rc.name = N'department_code') UPDATE s SET department_code = NULL FROM [dbo].[students] s LEFT JOIN [dbo].[departments] d ON d.department_code = s.department_code WHERE s.department_code IS NOT NULL AND d.department_code IS NULL;

IF OBJECT_ID(N'dbo.students', N'U') IS NOT NULL AND OBJECT_ID(N'dbo.departments', N'U') IS NOT NULL AND COL_LENGTH(N'dbo.students', N'department_code') IS NOT NULL AND COL_LENGTH(N'dbo.departments', N'department_code') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys.foreign_key_columns fkc INNER JOIN sys.columns pc ON fkc.parent_object_id = pc.object_id AND fkc.parent_column_id = pc.column_id INNER JOIN sys.columns rc ON fkc.referenced_object_id = rc.object_id AND fkc.referenced_column_id = rc.column_id WHERE fkc.parent_object_id = OBJECT_ID(N'dbo.students', N'U') AND pc.name = N'department_code' AND fkc.referenced_object_id = OBJECT_ID(N'dbo.departments', N'U') AND rc.name = N'department_code') ALTER TABLE [dbo].[students] ADD CONSTRAINT [FK_students_department_code] FOREIGN KEY ([department_code]) REFERENCES [dbo].[departments]([department_code]);
