// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ArchiveAttendanceSheet(arg1:number,arg2:string):Promise<void>;

export function ArchiveClass(arg1:number):Promise<void>;

export function ArchiveFeedback(arg1:Array<number>,arg2:number):Promise<number>;

export function ArchiveFeedbackByDate(arg1:string,arg2:number):Promise<number>;

export function ArchiveLogs(arg1:Array<number>,arg2:number):Promise<number>;

export function ArchiveLogsByDate(arg1:string,arg2:number):Promise<number>;

export function ChangePassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateClass(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:number):Promise<number>;

export function CreateDepartment(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateSubject(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function CreateUser(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string,arg12:string,arg13:string,arg14:string):Promise<void>;

export function CreateUsersBulk(arg1:string):Promise<Record<string, any>>;

export function CreateUsersBulkFromFile(arg1:string,arg2:string):Promise<Record<string, any>>;

export function DeleteAttendanceSheet(arg1:number,arg2:string):Promise<void>;

export function DeleteClass(arg1:number):Promise<void>;

export function DeleteDepartment(arg1:string):Promise<void>;

export function DeleteUser(arg1:number):Promise<void>;

export function DeleteUserProfilePhoto(arg1:number):Promise<void>;

export function EnrollMultipleStudents(arg1:Array<number>,arg2:number,arg3:number):Promise<void>;

export function EnrollStudentInClass(arg1:number,arg2:number,arg3:number):Promise<void>;

export function ExportArchivedFeedbackCSV():Promise<string>;

export function ExportArchivedFeedbackPDF():Promise<string>;

export function ExportArchivedFeedbackSheetCSV(arg1:string):Promise<string>;

export function ExportArchivedFeedbackSheetPDF(arg1:string):Promise<string>;

export function ExportArchivedLogSheetCSV(arg1:string):Promise<string>;

export function ExportArchivedLogSheetPDF(arg1:string):Promise<string>;

export function ExportArchivedLogsCSV():Promise<string>;

export function ExportArchivedLogsPDF():Promise<string>;

export function ExportAttendanceCSV(arg1:number):Promise<string>;

export function ExportFeedbackCSV():Promise<string>;

export function ExportFeedbackPDF():Promise<string>;

export function ExportLogsCSV():Promise<string>;

export function ExportLogsPDF():Promise<string>;

export function ForwardFeedbackToAdmin(arg1:number,arg2:number,arg3:string):Promise<void>;

export function ForwardMultipleFeedbackToAdmin(arg1:Array<number>,arg2:number,arg3:string):Promise<number>;

export function GenerateAttendanceFromLogs(arg1:number,arg2:string,arg3:number):Promise<void>;

export function GetAdminDashboard():Promise<main.AdminDashboard>;

export function GetAllClasses():Promise<Array<main.CourseClass>>;

export function GetAllLogs():Promise<Array<main.LoginLog>>;

export function GetAllRegisteredStudents(arg1:string,arg2:string):Promise<Array<main.ClassStudent>>;

export function GetAllStudentsForEnrollment(arg1:number):Promise<Array<main.ClassStudent>>;

export function GetAllTeachers():Promise<Array<main.User>>;

export function GetArchivedAttendanceSheets(arg1:number):Promise<Array<main.ArchivedAttendanceSheet>>;

export function GetArchivedClasses(arg1:number):Promise<Array<main.CourseClass>>;

export function GetArchivedFeedback():Promise<Array<main.Feedback>>;

export function GetArchivedFeedbackByDate(arg1:string):Promise<Array<main.Feedback>>;

export function GetArchivedFeedbackSheets():Promise<Array<main.ArchivedFeedbackSheet>>;

export function GetArchivedLogSheets():Promise<Array<main.ArchivedLogSheet>>;

export function GetArchivedLogs():Promise<Array<main.LoginLog>>;

export function GetArchivedLogsByDate(arg1:string):Promise<Array<main.LoginLog>>;

export function GetAvailableSections():Promise<Array<string>>;

export function GetAvailableStudents(arg1:number):Promise<Array<main.ClassStudent>>;

export function GetClassAttendance(arg1:number,arg2:string):Promise<Array<main.Attendance>>;

export function GetClassStudents(arg1:number):Promise<Array<main.ClasslistEntry>>;

export function GetClassesByCreator(arg1:number):Promise<Array<main.CourseClass>>;

export function GetClassesByEDPCode(arg1:string):Promise<Array<main.CourseClass>>;

export function GetDepartments():Promise<Array<main.Department>>;

export function GetFeedback():Promise<Array<main.Feedback>>;

export function GetFeedbackDates():Promise<Array<string>>;

export function GetLogDates():Promise<Array<string>>;

export function GetPendingFeedback():Promise<Array<main.Feedback>>;

export function GetRecentAttendance(arg1:Array<number>,arg2:number):Promise<Array<main.Attendance>>;

export function GetStudentClasses(arg1:number):Promise<Array<main.CourseClass>>;

export function GetStudentDashboard(arg1:number):Promise<main.StudentDashboard>;

export function GetStudentFeedback(arg1:number):Promise<Array<main.Feedback>>;

export function GetStudentLoginLogs(arg1:number):Promise<Array<main.LoginLog>>;

export function GetSubjects():Promise<Array<main.Subject>>;

export function GetTeacherClasses(arg1:number):Promise<Array<main.CourseClass>>;

export function GetTeacherClassesByUserID(arg1:number):Promise<Array<main.CourseClass>>;

export function GetTeacherClassesWithAttendance(arg1:number):Promise<Array<main.CourseClass>>;

export function GetTeacherDashboard(arg1:number):Promise<main.TeacherDashboard>;

export function GetTeacherID(arg1:number):Promise<number>;

export function GetTeacherLoginLogs(arg1:number):Promise<Array<main.LoginLog>>;

export function GetUsers():Promise<Array<main.User>>;

export function GetUsersByType(arg1:string):Promise<Array<main.User>>;

export function GetWorkingStudentDashboard():Promise<main.WorkingStudentDashboard>;

export function GetWorkingStudentID(arg1:number):Promise<number>;

export function InitializeAttendanceForClass(arg1:number,arg2:string,arg3:number):Promise<void>;

export function JoinClassByEDPCode(arg1:number,arg2:string):Promise<number>;

export function Login(arg1:string,arg2:string):Promise<main.User>;

export function Logout(arg1:number):Promise<void>;

export function RecordAttendance(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number):Promise<void>;

export function RecordStudentLogin(arg1:number,arg2:number,arg3:string):Promise<void>;

export function RecordTimeoutLogout(arg1:number):Promise<void>;

export function SaveEquipmentFeedback(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string):Promise<void>;

export function SearchUsers(arg1:string,arg2:string):Promise<Array<main.User>>;

export function UnarchiveAttendanceSheet(arg1:number,arg2:string):Promise<void>;

export function UnarchiveClass(arg1:number):Promise<void>;

export function UnarchiveFeedback(arg1:Array<number>):Promise<number>;

export function UnarchiveFeedbackSheet(arg1:string):Promise<number>;

export function UnarchiveLogSheet(arg1:string):Promise<number>;

export function UnarchiveLogs(arg1:Array<number>):Promise<number>;

export function UnenrollStudentFromClass(arg1:number):Promise<void>;

export function UnenrollStudentFromClassByIDs(arg1:number,arg2:number):Promise<void>;

export function UpdateAttendanceRecord(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<void>;

export function UpdateAttendanceTime(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UpdateClass(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:boolean):Promise<void>;

export function UpdateDepartment(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function UpdateUser(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string,arg12:string,arg13:string,arg14:string):Promise<void>;

export function UpdateUserPhoto(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateUserProfilePhoto(arg1:number,arg2:string):Promise<void>;
