// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateClass(arg1) {
  return window['go']['main']['App']['ActivateClass'](arg1);
}

export function ArchiveAttendanceSheet(arg1, arg2) {
  return window['go']['main']['App']['ArchiveAttendanceSheet'](arg1, arg2);
}

export function ArchiveClass(arg1) {
  return window['go']['main']['App']['ArchiveClass'](arg1);
}

export function ArchiveFeedback(arg1, arg2) {
  return window['go']['main']['App']['ArchiveFeedback'](arg1, arg2);
}

export function ArchiveFeedbackByDate(arg1, arg2) {
  return window['go']['main']['App']['ArchiveFeedbackByDate'](arg1, arg2);
}

export function ArchiveLogs(arg1, arg2) {
  return window['go']['main']['App']['ArchiveLogs'](arg1, arg2);
}

export function ArchiveLogsByDate(arg1, arg2) {
  return window['go']['main']['App']['ArchiveLogsByDate'](arg1, arg2);
}

export function ArchiveSelectedLogs(arg1, arg2) {
  return window['go']['main']['App']['ArchiveSelectedLogs'](arg1, arg2);
}

export function ArchiveStudent(arg1) {
  return window['go']['main']['App']['ArchiveStudent'](arg1);
}

export function ArchiveStudentEnrollment(arg1, arg2) {
  return window['go']['main']['App']['ArchiveStudentEnrollment'](arg1, arg2);
}

export function ChangePassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2, arg3);
}

export function CheckAttendanceExists(arg1, arg2) {
  return window['go']['main']['App']['CheckAttendanceExists'](arg1, arg2);
}

export function CloseAttendanceSession(arg1, arg2) {
  return window['go']['main']['App']['CloseAttendanceSession'](arg1, arg2);
}

export function CloseClass(arg1) {
  return window['go']['main']['App']['CloseClass'](arg1);
}

export function CreateAttendanceSession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateAttendanceSession'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateClass(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['CreateClass'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function CreateDepartment(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateDepartment'](arg1, arg2, arg3);
}

export function CreateSubject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateSubject'](arg1, arg2, arg3, arg4);
}

export function CreateUser(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['CreateUser'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function CreateUsersBulk(arg1) {
  return window['go']['main']['App']['CreateUsersBulk'](arg1);
}

export function CreateUsersBulkFromFile(arg1, arg2) {
  return window['go']['main']['App']['CreateUsersBulkFromFile'](arg1, arg2);
}

export function DeactivateClass(arg1) {
  return window['go']['main']['App']['DeactivateClass'](arg1);
}

export function DeleteClass(arg1) {
  return window['go']['main']['App']['DeleteClass'](arg1);
}

export function DeleteDepartment(arg1) {
  return window['go']['main']['App']['DeleteDepartment'](arg1);
}

export function DeleteExpiredStudents() {
  return window['go']['main']['App']['DeleteExpiredStudents']();
}

export function DeleteProfilePhoto(arg1) {
  return window['go']['main']['App']['DeleteProfilePhoto'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function DeleteUserProfilePhoto(arg1) {
  return window['go']['main']['App']['DeleteUserProfilePhoto'](arg1);
}

export function EnrollMultipleStudents(arg1, arg2, arg3) {
  return window['go']['main']['App']['EnrollMultipleStudents'](arg1, arg2, arg3);
}

export function EnrollStudentInClass(arg1, arg2, arg3) {
  return window['go']['main']['App']['EnrollStudentInClass'](arg1, arg2, arg3);
}

export function ExportArchivedFeedbackCSV() {
  return window['go']['main']['App']['ExportArchivedFeedbackCSV']();
}

export function ExportArchivedFeedbackPDF() {
  return window['go']['main']['App']['ExportArchivedFeedbackPDF']();
}

export function ExportArchivedFeedbackSheetCSV(arg1) {
  return window['go']['main']['App']['ExportArchivedFeedbackSheetCSV'](arg1);
}

export function ExportArchivedFeedbackSheetPDF(arg1) {
  return window['go']['main']['App']['ExportArchivedFeedbackSheetPDF'](arg1);
}

export function ExportArchivedLogSheetCSV(arg1) {
  return window['go']['main']['App']['ExportArchivedLogSheetCSV'](arg1);
}

export function ExportArchivedLogSheetPDF(arg1) {
  return window['go']['main']['App']['ExportArchivedLogSheetPDF'](arg1);
}

export function ExportArchivedLogsCSV() {
  return window['go']['main']['App']['ExportArchivedLogsCSV']();
}

export function ExportArchivedLogsPDF() {
  return window['go']['main']['App']['ExportArchivedLogsPDF']();
}

export function ExportAttendanceCSV(arg1) {
  return window['go']['main']['App']['ExportAttendanceCSV'](arg1);
}

export function ExportAttendanceCSVByDate(arg1, arg2) {
  return window['go']['main']['App']['ExportAttendanceCSVByDate'](arg1, arg2);
}

export function ExportClasslistCSV(arg1) {
  return window['go']['main']['App']['ExportClasslistCSV'](arg1);
}

export function ExportFeedbackCSV() {
  return window['go']['main']['App']['ExportFeedbackCSV']();
}

export function ExportFeedbackPDF() {
  return window['go']['main']['App']['ExportFeedbackPDF']();
}

export function ExportLogsCSV() {
  return window['go']['main']['App']['ExportLogsCSV']();
}

export function ExportLogsPDF() {
  return window['go']['main']['App']['ExportLogsPDF']();
}

export function ForwardFeedbackToAdmin(arg1, arg2, arg3) {
  return window['go']['main']['App']['ForwardFeedbackToAdmin'](arg1, arg2, arg3);
}

export function ForwardMultipleFeedbackToAdmin(arg1, arg2, arg3) {
  return window['go']['main']['App']['ForwardMultipleFeedbackToAdmin'](arg1, arg2, arg3);
}

export function GetActiveAttendanceSheets(arg1) {
  return window['go']['main']['App']['GetActiveAttendanceSheets'](arg1);
}

export function GetActiveStudentsForArchiving() {
  return window['go']['main']['App']['GetActiveStudentsForArchiving']();
}

export function GetAdminDashboard() {
  return window['go']['main']['App']['GetAdminDashboard']();
}

export function GetAllClasses() {
  return window['go']['main']['App']['GetAllClasses']();
}

export function GetAllLogs() {
  return window['go']['main']['App']['GetAllLogs']();
}

export function GetAllRegisteredStudents() {
  return window['go']['main']['App']['GetAllRegisteredStudents']();
}

export function GetAllStudentsForEnrollment(arg1) {
  return window['go']['main']['App']['GetAllStudentsForEnrollment'](arg1);
}

export function GetAllTeachers() {
  return window['go']['main']['App']['GetAllTeachers']();
}

export function GetArchivedAttendanceSheets(arg1) {
  return window['go']['main']['App']['GetArchivedAttendanceSheets'](arg1);
}

export function GetArchivedClasses(arg1) {
  return window['go']['main']['App']['GetArchivedClasses'](arg1);
}

export function GetArchivedFeedback() {
  return window['go']['main']['App']['GetArchivedFeedback']();
}

export function GetArchivedFeedbackByDate(arg1) {
  return window['go']['main']['App']['GetArchivedFeedbackByDate'](arg1);
}

export function GetArchivedFeedbackSheets() {
  return window['go']['main']['App']['GetArchivedFeedbackSheets']();
}

export function GetArchivedLogSheets() {
  return window['go']['main']['App']['GetArchivedLogSheets']();
}

export function GetArchivedLogs() {
  return window['go']['main']['App']['GetArchivedLogs']();
}

export function GetArchivedLogsByDate(arg1) {
  return window['go']['main']['App']['GetArchivedLogsByDate'](arg1);
}

export function GetArchivedStudents() {
  return window['go']['main']['App']['GetArchivedStudents']();
}

export function GetAvailableSections() {
  return window['go']['main']['App']['GetAvailableSections']();
}

export function GetAvailableStudents(arg1) {
  return window['go']['main']['App']['GetAvailableStudents'](arg1);
}

export function GetClassAttendance(arg1, arg2) {
  return window['go']['main']['App']['GetClassAttendance'](arg1, arg2);
}

export function GetClassByID(arg1) {
  return window['go']['main']['App']['GetClassByID'](arg1);
}

export function GetClassStudents(arg1) {
  return window['go']['main']['App']['GetClassStudents'](arg1);
}

export function GetClassesByCreator(arg1) {
  return window['go']['main']['App']['GetClassesByCreator'](arg1);
}

export function GetClassesByEDPCode(arg1) {
  return window['go']['main']['App']['GetClassesByEDPCode'](arg1);
}

export function GetCompletedEnrollments(arg1) {
  return window['go']['main']['App']['GetCompletedEnrollments'](arg1);
}

export function GetDepartments() {
  return window['go']['main']['App']['GetDepartments']();
}

export function GetFeedback() {
  return window['go']['main']['App']['GetFeedback']();
}

export function GetFeedbackDates() {
  return window['go']['main']['App']['GetFeedbackDates']();
}

export function GetInactiveClasses(arg1) {
  return window['go']['main']['App']['GetInactiveClasses'](arg1);
}

export function GetLogDates() {
  return window['go']['main']['App']['GetLogDates']();
}

export function GetPastLogs(arg1, arg2) {
  return window['go']['main']['App']['GetPastLogs'](arg1, arg2);
}

export function GetPendingFeedback() {
  return window['go']['main']['App']['GetPendingFeedback']();
}

export function GetPendingRegistrations() {
  return window['go']['main']['App']['GetPendingRegistrations']();
}

export function GetProfilePhotoURL(arg1) {
  return window['go']['main']['App']['GetProfilePhotoURL'](arg1);
}

export function GetRecentAttendance(arg1, arg2) {
  return window['go']['main']['App']['GetRecentAttendance'](arg1, arg2);
}

export function GetStudentArchivedClasses(arg1) {
  return window['go']['main']['App']['GetStudentArchivedClasses'](arg1);
}

export function GetStudentClasses(arg1) {
  return window['go']['main']['App']['GetStudentClasses'](arg1);
}

export function GetStudentDashboard(arg1) {
  return window['go']['main']['App']['GetStudentDashboard'](arg1);
}

export function GetStudentFeedback(arg1) {
  return window['go']['main']['App']['GetStudentFeedback'](arg1);
}

export function GetStudentLoginLogs(arg1) {
  return window['go']['main']['App']['GetStudentLoginLogs'](arg1);
}

export function GetStudentOpenAttendanceSessions(arg1) {
  return window['go']['main']['App']['GetStudentOpenAttendanceSessions'](arg1);
}

export function GetSubjects() {
  return window['go']['main']['App']['GetSubjects']();
}

export function GetTeacherAttendanceSessions(arg1) {
  return window['go']['main']['App']['GetTeacherAttendanceSessions'](arg1);
}

export function GetTeacherClasses(arg1) {
  return window['go']['main']['App']['GetTeacherClasses'](arg1);
}

export function GetTeacherClassesByUserID(arg1) {
  return window['go']['main']['App']['GetTeacherClassesByUserID'](arg1);
}

export function GetTeacherClassesWithAttendance(arg1) {
  return window['go']['main']['App']['GetTeacherClassesWithAttendance'](arg1);
}

export function GetTeacherDashboard(arg1) {
  return window['go']['main']['App']['GetTeacherDashboard'](arg1);
}

export function GetTeacherID(arg1) {
  return window['go']['main']['App']['GetTeacherID'](arg1);
}

export function GetTeacherLoginLogs(arg1) {
  return window['go']['main']['App']['GetTeacherLoginLogs'](arg1);
}

export function GetTodayLogs() {
  return window['go']['main']['App']['GetTodayLogs']();
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function GetUsersByType(arg1) {
  return window['go']['main']['App']['GetUsersByType'](arg1);
}

export function GetWorkingStudentDashboard() {
  return window['go']['main']['App']['GetWorkingStudentDashboard']();
}

export function GetWorkingStudentID(arg1) {
  return window['go']['main']['App']['GetWorkingStudentID'](arg1);
}

export function IsKioskMode() {
  return window['go']['main']['App']['IsKioskMode']();
}

export function JoinClassByEDPCode(arg1, arg2) {
  return window['go']['main']['App']['JoinClassByEDPCode'](arg1, arg2);
}

export function LockScreen() {
  return window['go']['main']['App']['LockScreen']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function MarkAllEnrollmentsCompleted(arg1) {
  return window['go']['main']['App']['MarkAllEnrollmentsCompleted'](arg1);
}

export function MarkEnrollmentCompleted(arg1, arg2) {
  return window['go']['main']['App']['MarkEnrollmentCompleted'](arg1, arg2);
}

export function MarkEnrollmentDropped(arg1, arg2) {
  return window['go']['main']['App']['MarkEnrollmentDropped'](arg1, arg2);
}

export function OpenAttendanceSession(arg1, arg2) {
  return window['go']['main']['App']['OpenAttendanceSession'](arg1, arg2);
}

export function OpenClassAttendance(arg1, arg2) {
  return window['go']['main']['App']['OpenClassAttendance'](arg1, arg2);
}

export function ProcessRegistration(arg1) {
  return window['go']['main']['App']['ProcessRegistration'](arg1);
}

export function ReactivateEnrollment(arg1, arg2) {
  return window['go']['main']['App']['ReactivateEnrollment'](arg1, arg2);
}

export function RecordTimeoutLogout(arg1) {
  return window['go']['main']['App']['RecordTimeoutLogout'](arg1);
}

export function RenameAttendanceSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameAttendanceSession'](arg1, arg2, arg3);
}

export function ReopenClass(arg1) {
  return window['go']['main']['App']['ReopenClass'](arg1);
}

export function SaveEquipmentFeedback(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['SaveEquipmentFeedback'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function SaveProfilePhoto(arg1, arg2) {
  return window['go']['main']['App']['SaveProfilePhoto'](arg1, arg2);
}

export function SearchUsers(arg1, arg2) {
  return window['go']['main']['App']['SearchUsers'](arg1, arg2);
}

export function SetClassActiveStatus(arg1, arg2) {
  return window['go']['main']['App']['SetClassActiveStatus'](arg1, arg2);
}

export function SetStudentEnrollmentStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetStudentEnrollmentStatus'](arg1, arg2, arg3);
}

export function StudentTimeIn(arg1, arg2) {
  return window['go']['main']['App']['StudentTimeIn'](arg1, arg2);
}

export function SubmitRegistration(arg1) {
  return window['go']['main']['App']['SubmitRegistration'](arg1);
}

export function UnarchiveAttendanceSheet(arg1, arg2) {
  return window['go']['main']['App']['UnarchiveAttendanceSheet'](arg1, arg2);
}

export function UnarchiveClass(arg1) {
  return window['go']['main']['App']['UnarchiveClass'](arg1);
}

export function UnarchiveFeedback(arg1) {
  return window['go']['main']['App']['UnarchiveFeedback'](arg1);
}

export function UnarchiveFeedbackSheet(arg1) {
  return window['go']['main']['App']['UnarchiveFeedbackSheet'](arg1);
}

export function UnarchiveLogSheet(arg1) {
  return window['go']['main']['App']['UnarchiveLogSheet'](arg1);
}

export function UnarchiveLogs(arg1) {
  return window['go']['main']['App']['UnarchiveLogs'](arg1);
}

export function UnarchiveStudent(arg1) {
  return window['go']['main']['App']['UnarchiveStudent'](arg1);
}

export function UnarchiveStudentEnrollment(arg1, arg2) {
  return window['go']['main']['App']['UnarchiveStudentEnrollment'](arg1, arg2);
}

export function UnenrollStudentFromClass(arg1) {
  return window['go']['main']['App']['UnenrollStudentFromClass'](arg1);
}

export function UnenrollStudentFromClassByIDs(arg1, arg2) {
  return window['go']['main']['App']['UnenrollStudentFromClassByIDs'](arg1, arg2);
}

export function UnlockScreen() {
  return window['go']['main']['App']['UnlockScreen']();
}

export function UpdateAttendanceRecord(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateAttendanceRecord'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateClass(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateClass'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function UpdateDepartment(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateDepartment'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateUser(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['UpdateUser'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function UpdateUserPhoto(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateUserPhoto'](arg1, arg2, arg3);
}

export function UpdateUserProfilePhoto(arg1, arg2) {
  return window['go']['main']['App']['UpdateUserProfilePhoto'](arg1, arg2);
}
